/**
 * Created by ttnd on 17/10/16.
 */
export const LIST_COURSES = "LIST_COURSES"
export const FETCHING_COURSES = "FETCHING_COURSES"
export const FECTCHING_COURSES_COMPLETED = "FECTCHING_COURSES_COMPLETED"
export const FETCHING_COMPLETE = "FETCHING_COMPLETE"
